---
# ansible-role-autofs/tasks/setup_Darwin.yml


# Install using homebrew
- name: "Setup | Darwin | homebrew | ensure autofs's package(s) present"
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: autofs_pkg_names
