---
# ansible-role-autofs/tasks/setup_Debian.yml


# Install from apt
- name: "Setup | Debian | ensure autofs's repo(s) present"
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: autofs_pkg_urls


- name: "Setup | Debian | ensure autofs's package(s) present"
  apt:
    name: "{{ item }}"
    state: present
    update_cache: "{{ autofs_pkg_cache_update }}"
    cache_valid_time: "{{ autofs_pkg_cache_time }}"
  with_items: autofs_pkg_names


# Download and install DEB file for Debian (Debian, Ubuntu, etc)
- name: "Setup | Debian | ensure temporary download dir can read, write, execute"
  file:
    path: "{{ autofs_dir_tmp_download }}"
    state: directory
    mode: "u+rwx"
    owner: "{{ ansible_ssh_user }}"

- name: "Setup | Debian | download autofs's deb file(s)"
  get_url:
    url: "{{ item.0 }}"
    dest: "{{ autofs_dir_tmp_download }}/{{ item.1 }}.deb"
  with_together:
    - autofs_pkg_urls
    - autofs_pkg_names

- name: "Setup | Debian | install autofs's deb file(s)"
  sudo: Yes
  apt:
    deb: "{{ autofs_dir_tmp_download }}/{{ item }}.deb"
  with_items: autofs_pkg_names