---
# ansible-role-autofs/tasks/Setup_Suse.yml


# Install using zypper
- name: "Setup | Suse   | ensure autofs's package(s) present"
  zypper:
    name: "{{ item }}"
    state: present
  with_items: autofs_pkg_names

