---
# ansible-role-autofs/tasks/setup.yml


- include: "setup_Darwin.yml"
  when: ansible_system == 'Darwin'

- include: "setup_FreeBSD.yml"
  when: ansible_system == 'FreeBSD'

- include: "setup_Linux_Debian.yml"
  when: ansible_os_family == 'Debian'

- include: "setup_Linux_RedHat.yml"
  when: ansible_os_family == 'RedHat'

- include: "setup_Linux_Suse.yml"
  when: ansible_os_family == 'Suse'
