---
# ansible-role-autofs/tasks/setup_Debian.yml


# Install from apt
- name: "Setup | Debian | ensure autofs's package(s) present"
  apt:
    name: "{{ item }}"
    state: present
    update_cache: "{{ autofs_pkg_cache_update }}"
    cache_valid_time: "{{ autofs_pkg_cache_time }}"
  with_items: autofs_pkg_names

