---
# ansible-role-autofs/tasks/vars.yml


# Look for distribution, os family, and then system. If none found. Error.
- name: "Vars  | ALL    | most specific OS variables available"
  include_vars: "{{ item }}"
  with_first_found:
    # - "{{ ansible_system }}_{{ ansible_os_family }}_{{ ansible_distribution }}.yml"
    # - "{{ ansible_system }}_{{ ansible_os_family }}.yml"
    - "{{ ansible_system }}.yml"


# Override OS variables
- name: "Vars  | ALL    | No override; set autofs_pkg_names to OS var"
  set_fact:
    autofs_pkg_names: "{{ __autofs_pkg_names }}"
  when: autofs_pkg_names is not defined  

